language: cpp

notifications:
  email: false

branches:
  except:
    - master

sudo: required

before_install:
  - docker --version || true
  - curl -fsSL https://get.docker.com/ | sudo bash
  - docker --version
  - docker pull b1f6c1c4/builder:$TRAVIS_BRANCH || true

script:
  - docker build --cache-from b1f6c1c4/builder:$TRAVIS_BRANCH -t b1f6c1c4/builder:$TRAVIS_BRANCH .

after_success:
  - printf "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push b1f6c1c4/builder:$TRAVIS_BRANCH
